tmdb-api-key: 96f9d761da098b39ca71e3484f860ff2
tmdb-external-api: https://api.themoviedb.org/3

server:
  servlet:
    context-path: /moviebook
  error:
    include-message: always
  port: '8081'
spring:
  data:
    mongodb:
      uri: mongodb://localhost/moviebook-database